ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  audience: "my-audience"
  realm: "my realm"
  issuer: "http://localhost"
  secret: "abcde"


  
