ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  audience: "my-audience"
  realm: "my realm"
  issuer: "http://localhost"
  secret: "abcde"

datasource:
  url: "jdbc:postgresql://localhost:5432/ktor_tutorial_db"
  user: "postgres"
  password: "password"
  driver: "org.postgresql.Driver"
